#!/bin/sh
# When configured within MPICH via PAC_CONFIG_SUBDIR, this file will be sourced
# by the top-level configure.  This lets us propagate shell variable changes
# back upstream.

CPPFLAGS="  -I/home/gavahi/boringssl-mvapich/src/mpl/include -I/home/gavahi/boringssl-mvapich/src/mpl/include -I/home/gavahi/boringssl-mvapich/src/openpa/src -I/home/gavahi/boringssl-mvapich/src/openpa/src -D_REENTRANT -I/home/gavahi/boringssl-mvapich/src/mpi/romio/include -I/include -I/include -I/include -I/include"
WRAPPER_LIBS="$WRAPPER_LIBS "
